package com.bit_etland.web.enums;

public enum Action {
	MOVE,REGISTER,ACCESS,SIGNUP,SIGNIN,
	CUSTOMER_LIST,CUST_RETRIEVE,CUST_UPDATE,CUST_FILE,CUST_FILE_UPLOAD,CUST_REMOVE,
	PRO_REGISTER,PRO_LIST,PRODUCT_RETRIEVE, CATE_LIST, CATEGORY_RETRIEVEL
	
}
